### ISSUE TITLE
Strange image result with digital persona u.are.u 4000

### ISSUE THREAD

**Issue by blob84** [Gnate/libfprint#2]
Hello, I've bought a digital persona u.are.u 4000.
I'm using Debian 9 64 bit.
Linux discover corretly the device.
I tried a libfprint example img_capture.c, it compiles and run but this is the image I've got:

![finger](https://user-images.githubusercontent.com/231464/38925621-71de488a-4300-11e8-8122-f96ab1eee642.jpg)

I don't know if it is a device problem or there are some options to get a better image.
What do you think?

**Comment by mattvasc** [comment]
I was also getting the same behavior in a number of randoms captures. 

Did you fix it? If so, how?
